/**
 * @file genx_ids_alert.c
 *
 * @brief This source file was generated by cantools version 40.4.0 Tue Sep  8 15:14:49 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "genx_ids_alert.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint32_t unpack_left_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint32_t unpack_right_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) >> shift);
}

int genx_ids_alert_ids_alert_pack(
    uint8_t *dst_p,
    const struct genx_ids_alert_ids_alert_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->violation_type, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u32(src_p->offending_id, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->offending_id, 8u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->offending_id, 16u, 0xffu);
    dst_p[4] |= pack_right_shift_u32(src_p->offending_id, 24u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->reserved1, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->reserved2, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->reserved3, 0u, 0xffu);

    return (8);
}

int genx_ids_alert_ids_alert_unpack(
    struct genx_ids_alert_ids_alert_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->violation_type = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->offending_id = unpack_right_shift_u32(src_p[1], 0u, 0xffu);
    dst_p->offending_id |= unpack_left_shift_u32(src_p[2], 8u, 0xffu);
    dst_p->offending_id |= unpack_left_shift_u32(src_p[3], 16u, 0xffu);
    dst_p->offending_id |= unpack_left_shift_u32(src_p[4], 24u, 0xffu);
    dst_p->reserved1 = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->reserved2 = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->reserved3 = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

int genx_ids_alert_ids_alert_init(struct genx_ids_alert_ids_alert_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct genx_ids_alert_ids_alert_t));

    return 0;
}

uint8_t genx_ids_alert_ids_alert_violation_type_encode(double value)
{
    return (uint8_t)(value);
}

double genx_ids_alert_ids_alert_violation_type_decode(uint8_t value)
{
    return ((double)value);
}

bool genx_ids_alert_ids_alert_violation_type_is_in_range(uint8_t value)
{
    return (value <= 4u);
}

uint32_t genx_ids_alert_ids_alert_offending_id_encode(double value)
{
    return (uint32_t)(value);
}

double genx_ids_alert_ids_alert_offending_id_decode(uint32_t value)
{
    return ((double)value);
}

bool genx_ids_alert_ids_alert_offending_id_is_in_range(uint32_t value)
{
    return (value <= 536870911u);
}

uint8_t genx_ids_alert_ids_alert_reserved1_encode(double value)
{
    return (uint8_t)(value);
}

double genx_ids_alert_ids_alert_reserved1_decode(uint8_t value)
{
    return ((double)value);
}

bool genx_ids_alert_ids_alert_reserved1_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t genx_ids_alert_ids_alert_reserved2_encode(double value)
{
    return (uint8_t)(value);
}

double genx_ids_alert_ids_alert_reserved2_decode(uint8_t value)
{
    return ((double)value);
}

bool genx_ids_alert_ids_alert_reserved2_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t genx_ids_alert_ids_alert_reserved3_encode(double value)
{
    return (uint8_t)(value);
}

double genx_ids_alert_ids_alert_reserved3_decode(uint8_t value)
{
    return ((double)value);
}

bool genx_ids_alert_ids_alert_reserved3_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}
