/*
 * genx_simulink_bridge.c
 * Auto-generated by SmartWheels GenX Ã¢â‚¬â€� DO NOT EDIT
 * Model : ACC
 * Date  : 2026-06-15
 */

#include "genx_simulink_bridge.h"
#include "genx_common.h"


/* -------------------------------------------------------------- */
void ANCIT_App_Init(void)
{
    ACC_initialize();
}

/* -------------------------------------------------------------- */
void ANCIT_App_PreStep(void)
{
    ACC_U.Distance = ((real_T)(ggenx.Ultra_Distance));
    ACC_U.V_set = ((real_T)(ggenx.Vset));
    ACC_U.D_min = ((real_T)(ggenx.Dmin));
}

void ANCIT_App_PreStep_Dspace(void)
{
    ACC_U.Distance = ((real_T)(ggenx.ACC_Obj));
    ACC_U.V_set = ((real_T)((ggenx.ACC_Vset > 100U) ? 100U : ggenx.ACC_Vset));
    ACC_U.D_min = ((real_T)(ggenx.ACC_Dmin));
}

/* -------------------------------------------------------------- */
void ANCIT_App_PostStep(void)
{
    ggenx.PWM = ACC_Y.PWM;
}

/*
 * Scheduler runnable body (add to your task in Scheduler tab):
 *
 *   ANCIT_App_PreStep();
 *   ACC_step();
 *   ANCIT_App_PostStep();
 */
