/*
 * genx_simulink_bridge.h
 * Auto-generated by SmartWheels GenX Ã¢â‚¬â€� DO NOT EDIT
 * Model : ACC
 * Date  : 2026-06-15
 */

#ifndef GENX_SIMULINK_BRIDGE_H
#define GENX_SIMULINK_BRIDGE_H

#ifdef __cplusplus
extern "C" {
#endif

/* Include the Simulink-generated header */
#include "ACC.h"

/**
 * Copy BSW signal values into ExtU (inputs to Simulink model).
 * Call this BEFORE ACC_step().
 */
void ANCIT_App_PreStep(void);

void ANCIT_App_PreStep_Dspace(void);

/**
 * Read ExtY (outputs from Simulink model) and write to BSW signals.
 * Call this AFTER ACC_step().
 */
void ANCIT_App_PostStep(void);

/**
 * Call ACC_initialize() Ã¢â‚¬â€� invoke once during board initialisation.
 */
void ANCIT_App_Init(void);

#ifdef __cplusplus
}
#endif

#endif /* GENX_SIMULINK_BRIDGE_H */
