/**
 * @file smartwheels_rover.h
 *
 * @brief This header file was generated by cantools version 40.4.0 Wed Aug 19 14:46:07 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef SMARTWHEELS_ROVER_H
#define SMARTWHEELS_ROVER_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define SMARTWHEELS_ROVER_ROVER_ACC_STATUS_FRAME_ID (0x301u)
#define SMARTWHEELS_ROVER_ROVER_ACC_PARAM_FRAME_ID (0x202u)
#define SMARTWHEELS_ROVER_ROVER_VEHICLE_CMD_FRAME_ID (0x201u)

/* Frame lengths in bytes. */
#define SMARTWHEELS_ROVER_ROVER_ACC_STATUS_LENGTH (5u)
#define SMARTWHEELS_ROVER_ROVER_ACC_PARAM_LENGTH (4u)
#define SMARTWHEELS_ROVER_ROVER_VEHICLE_CMD_LENGTH (2u)

/* Extended or standard frame types. */
#define SMARTWHEELS_ROVER_ROVER_ACC_STATUS_IS_EXTENDED (0)
#define SMARTWHEELS_ROVER_ROVER_ACC_PARAM_IS_EXTENDED (0)
#define SMARTWHEELS_ROVER_ROVER_VEHICLE_CMD_IS_EXTENDED (0)

/* Frame cycle times in milliseconds. */


/* Signal choices. */
#define SMARTWHEELS_ROVER_ROVER_VEHICLE_CMD_DIRECTION_CMD_NEUTRAL_CHOICE (0u)
#define SMARTWHEELS_ROVER_ROVER_VEHICLE_CMD_DIRECTION_CMD_DRIVE_CHOICE (1u)
#define SMARTWHEELS_ROVER_ROVER_VEHICLE_CMD_DIRECTION_CMD_REVERSE_CHOICE (2u)

#define SMARTWHEELS_ROVER_ROVER_VEHICLE_CMD_ACC_ENABLE_DISABLE_CHOICE (0u)
#define SMARTWHEELS_ROVER_ROVER_VEHICLE_CMD_ACC_ENABLE_ENABLE_CHOICE (3u)

#define SMARTWHEELS_ROVER_ROVER_VEHICLE_CMD_VACC_ENABLE_DISABLE_CHOICE (0u)
#define SMARTWHEELS_ROVER_ROVER_VEHICLE_CMD_VACC_ENABLE_ENABLE_CHOICE (3u)

/* Frame Names. */
#define SMARTWHEELS_ROVER_ROVER_ACC_STATUS_NAME "ROVER_ACC_STATUS"
#define SMARTWHEELS_ROVER_ROVER_ACC_PARAM_NAME "ROVER_ACC_PARAM"
#define SMARTWHEELS_ROVER_ROVER_VEHICLE_CMD_NAME "ROVER_VEHICLE_CMD"

/* Signal Names. */
#define SMARTWHEELS_ROVER_ROVER_ACC_STATUS_PWM_NAME "PWM"
#define SMARTWHEELS_ROVER_ROVER_ACC_STATUS_REAL_VSET_NAME "RealVset"
#define SMARTWHEELS_ROVER_ROVER_ACC_STATUS_REAL_DMIN_NAME "RealDmin"
#define SMARTWHEELS_ROVER_ROVER_ACC_STATUS_REAL_OBJ_NAME "RealObj"
#define SMARTWHEELS_ROVER_ROVER_ACC_PARAM_ACC_V_SET_NAME "ACC_VSet"
#define SMARTWHEELS_ROVER_ROVER_ACC_PARAM_ACC_D_MIN_NAME "ACC_DMin"
#define SMARTWHEELS_ROVER_ROVER_ACC_PARAM_ACC_VIRT_OBJ_DIST_NAME "ACC_VirtObjDist"
#define SMARTWHEELS_ROVER_ROVER_VEHICLE_CMD_DIRECTION_CMD_NAME "DirectionCmd"
#define SMARTWHEELS_ROVER_ROVER_VEHICLE_CMD_ACC_ENABLE_NAME "ACC_Enable"
#define SMARTWHEELS_ROVER_ROVER_VEHICLE_CMD_VACC_ENABLE_NAME "VACC_Enable"
#define SMARTWHEELS_ROVER_ROVER_VEHICLE_CMD_SPEED_CMD_NAME "SpeedCmd"

/**
 * Signals in message ROVER_ACC_STATUS.
 *
 * All signal values are as on the CAN bus.
 */
struct smartwheels_rover_rover_acc_status_t {
    /**
     * Range: 0..100 (0..100 %)
     * Scale: 1
     * Offset: 0
     */
    uint8_t pwm;

    /**
     * Range: 0..100 (0..100 Km/h)
     * Scale: 1
     * Offset: 0
     */
    uint8_t real_vset;

    /**
     * Range: 0..255 (0..255 m)
     * Scale: 1
     * Offset: 0
     */
    uint8_t real_dmin;

    /**
     * Range: 0..65535 (0..65535 m)
     * Scale: 1
     * Offset: 0
     */
    uint16_t real_obj;
};

/**
 * Signals in message ROVER_ACC_PARAM.
 *
 * All signal values are as on the CAN bus.
 */
struct smartwheels_rover_rover_acc_param_t {
    /**
     * Range: 0..100 (0..100 Km/h)
     * Scale: 1
     * Offset: 0
     */
    uint8_t acc_v_set;

    /**
     * Range: 0..255 (0..255 m)
     * Scale: 1
     * Offset: 0
     */
    uint8_t acc_d_min;

    /**
     * Range: 0..65535 (0..65535 m)
     * Scale: 1
     * Offset: 0
     */
    uint16_t acc_virt_obj_dist;
};

/**
 * Signals in message ROVER_VEHICLE_CMD.
 *
 * All signal values are as on the CAN bus.
 */
struct smartwheels_rover_rover_vehicle_cmd_t {
    /**
     * Range: 0..3 (0..3 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t direction_cmd;

    /**
     * Range: 0..3 (0..3 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t acc_enable;

    /**
     * Range: 0..3 (0..3 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t vacc_enable;

    /**
     * Range: 0..100 (0..100 Km/h)
     * Scale: 1
     * Offset: 0
     */
    uint8_t speed_cmd;
};

/**
 * Pack message ROVER_ACC_STATUS.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int smartwheels_rover_rover_acc_status_pack(
    uint8_t *dst_p,
    const struct smartwheels_rover_rover_acc_status_t *src_p,
    size_t size);

/**
 * Unpack message ROVER_ACC_STATUS.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int smartwheels_rover_rover_acc_status_unpack(
    struct smartwheels_rover_rover_acc_status_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from ROVER_ACC_STATUS.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int smartwheels_rover_rover_acc_status_init(struct smartwheels_rover_rover_acc_status_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t smartwheels_rover_rover_acc_status_pwm_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double smartwheels_rover_rover_acc_status_pwm_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool smartwheels_rover_rover_acc_status_pwm_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t smartwheels_rover_rover_acc_status_real_vset_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double smartwheels_rover_rover_acc_status_real_vset_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool smartwheels_rover_rover_acc_status_real_vset_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t smartwheels_rover_rover_acc_status_real_dmin_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double smartwheels_rover_rover_acc_status_real_dmin_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool smartwheels_rover_rover_acc_status_real_dmin_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t smartwheels_rover_rover_acc_status_real_obj_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double smartwheels_rover_rover_acc_status_real_obj_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool smartwheels_rover_rover_acc_status_real_obj_is_in_range(uint16_t value);

/**
 * Pack message ROVER_ACC_PARAM.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int smartwheels_rover_rover_acc_param_pack(
    uint8_t *dst_p,
    const struct smartwheels_rover_rover_acc_param_t *src_p,
    size_t size);

/**
 * Unpack message ROVER_ACC_PARAM.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int smartwheels_rover_rover_acc_param_unpack(
    struct smartwheels_rover_rover_acc_param_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from ROVER_ACC_PARAM.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int smartwheels_rover_rover_acc_param_init(struct smartwheels_rover_rover_acc_param_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t smartwheels_rover_rover_acc_param_acc_v_set_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double smartwheels_rover_rover_acc_param_acc_v_set_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool smartwheels_rover_rover_acc_param_acc_v_set_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t smartwheels_rover_rover_acc_param_acc_d_min_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double smartwheels_rover_rover_acc_param_acc_d_min_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool smartwheels_rover_rover_acc_param_acc_d_min_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t smartwheels_rover_rover_acc_param_acc_virt_obj_dist_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double smartwheels_rover_rover_acc_param_acc_virt_obj_dist_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool smartwheels_rover_rover_acc_param_acc_virt_obj_dist_is_in_range(uint16_t value);

/**
 * Pack message ROVER_VEHICLE_CMD.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int smartwheels_rover_rover_vehicle_cmd_pack(
    uint8_t *dst_p,
    const struct smartwheels_rover_rover_vehicle_cmd_t *src_p,
    size_t size);

/**
 * Unpack message ROVER_VEHICLE_CMD.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int smartwheels_rover_rover_vehicle_cmd_unpack(
    struct smartwheels_rover_rover_vehicle_cmd_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from ROVER_VEHICLE_CMD.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int smartwheels_rover_rover_vehicle_cmd_init(struct smartwheels_rover_rover_vehicle_cmd_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t smartwheels_rover_rover_vehicle_cmd_direction_cmd_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double smartwheels_rover_rover_vehicle_cmd_direction_cmd_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool smartwheels_rover_rover_vehicle_cmd_direction_cmd_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t smartwheels_rover_rover_vehicle_cmd_acc_enable_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double smartwheels_rover_rover_vehicle_cmd_acc_enable_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool smartwheels_rover_rover_vehicle_cmd_acc_enable_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t smartwheels_rover_rover_vehicle_cmd_vacc_enable_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double smartwheels_rover_rover_vehicle_cmd_vacc_enable_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool smartwheels_rover_rover_vehicle_cmd_vacc_enable_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t smartwheels_rover_rover_vehicle_cmd_speed_cmd_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double smartwheels_rover_rover_vehicle_cmd_speed_cmd_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool smartwheels_rover_rover_vehicle_cmd_speed_cmd_is_in_range(uint8_t value);


#ifdef __cplusplus
}
#endif

#endif
