/**
 * @file genx_ids_alert.h
 *
 * @brief This header file was generated by cantools version 40.4.0 Tue Sep  8 15:14:49 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef GENX_IDS_ALERT_H
#define GENX_IDS_ALERT_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define GENX_IDS_ALERT_IDS_ALERT_FRAME_ID (0x7ffu)

/* Frame lengths in bytes. */
#define GENX_IDS_ALERT_IDS_ALERT_LENGTH (8u)

/* Extended or standard frame types. */
#define GENX_IDS_ALERT_IDS_ALERT_IS_EXTENDED (0)

/* Frame cycle times in milliseconds. */


/* Signal choices. */
#define GENX_IDS_ALERT_IDS_ALERT_VIOLATION_TYPE_NO__VIOLATION_CHOICE (0u)
#define GENX_IDS_ALERT_IDS_ALERT_VIOLATION_TYPE_UNKNOWN_CAN_ID_CHOICE (1u)
#define GENX_IDS_ALERT_IDS_ALERT_VIOLATION_TYPE_DLC__MISMATCH_CHOICE (2u)
#define GENX_IDS_ALERT_IDS_ALERT_VIOLATION_TYPE_TIMING__VIOLATION_CHOICE (3u)
#define GENX_IDS_ALERT_IDS_ALERT_VIOLATION_TYPE_SIGNAL__RANGE__VIOLATION_CHOICE (4u)

/* Frame Names. */
#define GENX_IDS_ALERT_IDS_ALERT_NAME "IDS_Alert"

/* Signal Names. */
#define GENX_IDS_ALERT_IDS_ALERT_VIOLATION_TYPE_NAME "ViolationType"
#define GENX_IDS_ALERT_IDS_ALERT_OFFENDING_ID_NAME "OffendingId"
#define GENX_IDS_ALERT_IDS_ALERT_RESERVED1_NAME "Reserved1"
#define GENX_IDS_ALERT_IDS_ALERT_RESERVED2_NAME "Reserved2"
#define GENX_IDS_ALERT_IDS_ALERT_RESERVED3_NAME "Reserved3"

/**
 * Signals in message IDS_Alert.
 *
 * CAN Intrusion Detection System (IDS) alert message. Sent when a CAN bus violation is detected by the GenX IDS module.
 *
 * All signal values are as on the CAN bus.
 */
struct genx_ids_alert_ids_alert_t {
    /**
     * Type of IDS violation detected: 0=None, 1=Unknown ID, 2=DLC Mismatch, 3=Timing Violation, 4=Signal Range Violation
     *
     * Range: 0..4 (0..4 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t violation_type;

    /**
     * The CAN ID of the message that triggered the violation (big-endian: Byte1=MSB, Byte4=LSB)
     *
     * Range: 0..536870911 (0..536870911 -)
     * Scale: 1
     * Offset: 0
     */
    uint32_t offending_id;

    /**
     * Reserved for future use
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t reserved1;

    /**
     * Reserved for future use
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t reserved2;

    /**
     * Reserved for future use
     *
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t reserved3;
};

/**
 * Pack message IDS_Alert.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int genx_ids_alert_ids_alert_pack(
    uint8_t *dst_p,
    const struct genx_ids_alert_ids_alert_t *src_p,
    size_t size);

/**
 * Unpack message IDS_Alert.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int genx_ids_alert_ids_alert_unpack(
    struct genx_ids_alert_ids_alert_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from IDS_Alert.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int genx_ids_alert_ids_alert_init(struct genx_ids_alert_ids_alert_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t genx_ids_alert_ids_alert_violation_type_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double genx_ids_alert_ids_alert_violation_type_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool genx_ids_alert_ids_alert_violation_type_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint32_t genx_ids_alert_ids_alert_offending_id_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double genx_ids_alert_ids_alert_offending_id_decode(uint32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool genx_ids_alert_ids_alert_offending_id_is_in_range(uint32_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t genx_ids_alert_ids_alert_reserved1_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double genx_ids_alert_ids_alert_reserved1_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool genx_ids_alert_ids_alert_reserved1_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t genx_ids_alert_ids_alert_reserved2_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double genx_ids_alert_ids_alert_reserved2_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool genx_ids_alert_ids_alert_reserved2_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t genx_ids_alert_ids_alert_reserved3_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double genx_ids_alert_ids_alert_reserved3_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool genx_ids_alert_ids_alert_reserved3_is_in_range(uint8_t value);


#ifdef __cplusplus
}
#endif

#endif
