/**
 * @file smartwheels_rover.c
 *
 * @brief This source file was generated by cantools version 40.4.0 Wed Aug 19 14:46:07 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "smartwheels_rover.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

int smartwheels_rover_rover_acc_status_pack(
    uint8_t *dst_p,
    const struct smartwheels_rover_rover_acc_status_t *src_p,
    size_t size)
{
    if (size < 5u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 5);

    dst_p[0] |= pack_left_shift_u8(src_p->pwm, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->real_vset, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->real_dmin, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->real_obj, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->real_obj, 8u, 0xffu);

    return (5);
}

int smartwheels_rover_rover_acc_status_unpack(
    struct smartwheels_rover_rover_acc_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 5u) {
        return (-EINVAL);
    }

    dst_p->pwm = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->real_vset = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->real_dmin = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->real_obj = unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->real_obj |= unpack_left_shift_u16(src_p[4], 8u, 0xffu);

    return (0);
}

int smartwheels_rover_rover_acc_status_init(struct smartwheels_rover_rover_acc_status_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct smartwheels_rover_rover_acc_status_t));

    return 0;
}

uint8_t smartwheels_rover_rover_acc_status_pwm_encode(double value)
{
    return (uint8_t)(value);
}

double smartwheels_rover_rover_acc_status_pwm_decode(uint8_t value)
{
    return ((double)value);
}

bool smartwheels_rover_rover_acc_status_pwm_is_in_range(uint8_t value)
{
    return (value <= 100u);
}

uint8_t smartwheels_rover_rover_acc_status_real_vset_encode(double value)
{
    return (uint8_t)(value);
}

double smartwheels_rover_rover_acc_status_real_vset_decode(uint8_t value)
{
    return ((double)value);
}

bool smartwheels_rover_rover_acc_status_real_vset_is_in_range(uint8_t value)
{
    return (value <= 100u);
}

uint8_t smartwheels_rover_rover_acc_status_real_dmin_encode(double value)
{
    return (uint8_t)(value);
}

double smartwheels_rover_rover_acc_status_real_dmin_decode(uint8_t value)
{
    return ((double)value);
}

bool smartwheels_rover_rover_acc_status_real_dmin_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint16_t smartwheels_rover_rover_acc_status_real_obj_encode(double value)
{
    return (uint16_t)(value);
}

double smartwheels_rover_rover_acc_status_real_obj_decode(uint16_t value)
{
    return ((double)value);
}

bool smartwheels_rover_rover_acc_status_real_obj_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int smartwheels_rover_rover_acc_param_pack(
    uint8_t *dst_p,
    const struct smartwheels_rover_rover_acc_param_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    dst_p[0] |= pack_left_shift_u8(src_p->acc_v_set, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->acc_d_min, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->acc_virt_obj_dist, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->acc_virt_obj_dist, 8u, 0xffu);

    return (4);
}

int smartwheels_rover_rover_acc_param_unpack(
    struct smartwheels_rover_rover_acc_param_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    dst_p->acc_v_set = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->acc_d_min = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->acc_virt_obj_dist = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->acc_virt_obj_dist |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);

    return (0);
}

int smartwheels_rover_rover_acc_param_init(struct smartwheels_rover_rover_acc_param_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct smartwheels_rover_rover_acc_param_t));

    return 0;
}

uint8_t smartwheels_rover_rover_acc_param_acc_v_set_encode(double value)
{
    return (uint8_t)(value);
}

double smartwheels_rover_rover_acc_param_acc_v_set_decode(uint8_t value)
{
    return ((double)value);
}

bool smartwheels_rover_rover_acc_param_acc_v_set_is_in_range(uint8_t value)
{
    return (value <= 100u);
}

uint8_t smartwheels_rover_rover_acc_param_acc_d_min_encode(double value)
{
    return (uint8_t)(value);
}

double smartwheels_rover_rover_acc_param_acc_d_min_decode(uint8_t value)
{
    return ((double)value);
}

bool smartwheels_rover_rover_acc_param_acc_d_min_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint16_t smartwheels_rover_rover_acc_param_acc_virt_obj_dist_encode(double value)
{
    return (uint16_t)(value);
}

double smartwheels_rover_rover_acc_param_acc_virt_obj_dist_decode(uint16_t value)
{
    return ((double)value);
}

bool smartwheels_rover_rover_acc_param_acc_virt_obj_dist_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int smartwheels_rover_rover_vehicle_cmd_pack(
    uint8_t *dst_p,
    const struct smartwheels_rover_rover_vehicle_cmd_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    dst_p[0] |= pack_left_shift_u8(src_p->direction_cmd, 0u, 0x03u);
    dst_p[0] |= pack_left_shift_u8(src_p->acc_enable, 2u, 0x0cu);
    dst_p[0] |= pack_left_shift_u8(src_p->vacc_enable, 4u, 0x30u);
    dst_p[1] |= pack_left_shift_u8(src_p->speed_cmd, 0u, 0xffu);

    return (2);
}

int smartwheels_rover_rover_vehicle_cmd_unpack(
    struct smartwheels_rover_rover_vehicle_cmd_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 2u) {
        return (-EINVAL);
    }

    dst_p->direction_cmd = unpack_right_shift_u8(src_p[0], 0u, 0x03u);
    dst_p->acc_enable = unpack_right_shift_u8(src_p[0], 2u, 0x0cu);
    dst_p->vacc_enable = unpack_right_shift_u8(src_p[0], 4u, 0x30u);
    dst_p->speed_cmd = unpack_right_shift_u8(src_p[1], 0u, 0xffu);

    return (0);
}

int smartwheels_rover_rover_vehicle_cmd_init(struct smartwheels_rover_rover_vehicle_cmd_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct smartwheels_rover_rover_vehicle_cmd_t));

    return 0;
}

uint8_t smartwheels_rover_rover_vehicle_cmd_direction_cmd_encode(double value)
{
    return (uint8_t)(value);
}

double smartwheels_rover_rover_vehicle_cmd_direction_cmd_decode(uint8_t value)
{
    return ((double)value);
}

bool smartwheels_rover_rover_vehicle_cmd_direction_cmd_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t smartwheels_rover_rover_vehicle_cmd_acc_enable_encode(double value)
{
    return (uint8_t)(value);
}

double smartwheels_rover_rover_vehicle_cmd_acc_enable_decode(uint8_t value)
{
    return ((double)value);
}

bool smartwheels_rover_rover_vehicle_cmd_acc_enable_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t smartwheels_rover_rover_vehicle_cmd_vacc_enable_encode(double value)
{
    return (uint8_t)(value);
}

double smartwheels_rover_rover_vehicle_cmd_vacc_enable_decode(uint8_t value)
{
    return ((double)value);
}

bool smartwheels_rover_rover_vehicle_cmd_vacc_enable_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t smartwheels_rover_rover_vehicle_cmd_speed_cmd_encode(double value)
{
    return (uint8_t)(value);
}

double smartwheels_rover_rover_vehicle_cmd_speed_cmd_decode(uint8_t value)
{
    return ((double)value);
}

bool smartwheels_rover_rover_vehicle_cmd_speed_cmd_is_in_range(uint8_t value)
{
    return (value <= 100u);
}
