/***********************************************************************************************************************
 * This file was generated by the S32 Configuration Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Configuration Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v14.0
processor: S32K144
package_id: S32K144_LQFP100
mcu_data: s32sdk_s32k1xx_rtm_401
processor_version: 0.0.0
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: f680c506-f49b-4dfd-bc04-f34aa7a60054
  called_from_default_init: true
  selectedCore: core0
- name: VS_0
  UUID: a6d43dcb-893a-49cd-9d9d-0bb26ff0f05b
  selectedCore: core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/*******************************************************************************
 * Included files 
 ******************************************************************************/
#include "peripherals_flexTimer_ic_echo.h"

/*******************************************************************************
 * flexTimer_ic_echo initialization code
 ******************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'flexTimer_ic_echo'
- type: 'flexTimer_ic'
- mode: 'general'
- custom_name_enabled: 'true'
- type_id: 'ftm_ic'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'FTM_2'
- config_sets:
  - ftm_ic:
    - totalConfiguration:
      - ftmUserConfig:
        - ClockSource: 'FTM_CLOCK_SOURCE_EXTERNALCLK'
        - ClockSourcePrescaler: '8'
        - DebugMode: 'FTM_BDM_MODE_11'
        - TimerOverInterrupt: 'true'
        - InitializationTrigger: 'false'
      - icConfiguration:
        - numofChannel: '1'
        - maxCountVal: '65535'
        - arrayicConfig:
          - 0:
            - configName: 'flexTimer_ic_echo_ChannelConfig0'
            - hwID: '2'
            - operationMode: 'FTM_SIGNAL_MEASUREMENT'
            - edgeDetectMode: 'FTM_RISING_EDGE'
            - measureMode: 'FTM_PERIOD_ON_MEASUREMENT'
            - continousMode: 'true'
            - inputCaptureFilter: 'false'
            - inputCaptureFilterValue: '0'
            - callback: 'callback_echo_received'
            - callbackParameter: 'NULL'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.7, External variable could be made static.
 * The external variables will be used in other source files in application code.
 *
 */

/* Global configuration of flexTimer_ic_echo InitConfig */
ftm_user_config_t flexTimer_ic_echo_InitConfig =
{
    {
        true,    /* Software trigger state */
        false,  /* Hardware trigger 1 state */
        false,  /* Hardware trigger 2 state */
        false,  /* Hardware trigger 3 state */
        false, /* Max loading point state */
        false, /* Min loading point state */
        FTM_SYSTEM_CLOCK, /* Update mode for INVCTRL register */
        FTM_SYSTEM_CLOCK, /* Update mode for SWOCTRL register */
        FTM_SYSTEM_CLOCK, /* Update mode for OUTMASK register */
        FTM_SYSTEM_CLOCK, /* Update mode for CNTIN register */
        false, /* Automatic clear of the trigger */
        FTM_UPDATE_NOW, /* Synchronization point */
    },
        FTM_MODE_INPUT_CAPTURE, /* Mode of operation for FTM */
        FTM_CLOCK_DIVID_BY_8, /* FTM clock prescaler */
        FTM_CLOCK_SOURCE_EXTERNALCLK,   /* FTM clock source */
        FTM_BDM_MODE_11, /* FTM debug mode */
        true,    /* Interrupt state */
        false     /* Initialization trigger */
};

/* Input capture configuration for flexTimer_ic_echo */
ftm_input_param_t flexTimer_ic_echo_InputCaptureConfig =
{
    1U, /* Number of channel configurations */
    65535U, /* Maximum count value */
    flexTimer_ic_echo_InputCaptureChannelConfig /* Channels configuration*/
};

/* Callback function of channel configuration 0 */
extern void callback_echo_received(ic_event_t event, void *userData);

/* Channels configuration structure for flexTimer_ic_echo input capture */
ftm_input_ch_param_t flexTimer_ic_echo_InputCaptureChannelConfig[1] =
{
    {
        2U, /* Channel id */
        FTM_SIGNAL_MEASUREMENT, /* Input capture operation mode */
        FTM_RISING_EDGE, /* Edge alignment mode */
        FTM_PERIOD_ON_MEASUREMENT, /* Signal measurement operation type */
        0U, /* Filter value */
        false, /* Filter state (enabled/disabled) */
        true, /* Continuous measurement state */
        NULL, /* Vector of callbacks  parameters for channels events */
        callback_echo_received /* Vector of callbacks for channels events */
    }
};


